### ISSUE TITLE
timestamp field issues - PutInfluxDatabaseRecord_2

### ISSUE THREAD

**Issue by oneofthemany** [influxdata/nifi-influxdb-bundle#132]
Processor Version: 1.25.0-SNAPSHOT

i seem to have an issue when using NiFI and Influx DB.

I am using the UpdateAttribute processor to convert epoch time to a format which will be readable by the Influx DB processor:

```
time
2023-09-12 15:55:01.242Z
No value set
timestamp
2023-09-12 15:55:01.242Z
1694534101242 (previous)
```

both attributes are the same in terms of value against the property:

`${timestamp:formatInstant("yyyy-MM-dd HH:mm:ss.SSS'Z'", "GMT")}`

the only difference between time and timestamp is that I have a field called timestamp within my json data:

{"timestamp":1694534104820,...}

its very strange as if the time field name follows the attribute "time"  it sends data to the DB, and if I use the attribute "timestamp" it does not

for further information, if I use the attribute "timestamp" and its old buffered data it drops the data and gives the following error:

```
15:49:31 UTC  ERROR 
PutInfluxDatabaseRecord_2[id=018a1001-f95d-1a8c-7c43-630db8f73944] Failed to insert into influxDB due to HTTP status code: 422; Message: failure writing points to database: partial write: points beyond retention policy dropped=1: com.influxdb.exceptions.UnprocessableEntityException: HTTP status code: 422; Message: failure writing points to database: partial write: points beyond retention policy dropped=1
```

which again makes no sense as the buckets retention is set to forever:

![Screenshot from 2023-09-12 17-11-43](https://github.com/influxdata/nifi-influxdb-bundle/assets/44924639/44e176f7-9b2f-4397-8a60-81056a3f4dde)

then to make things even weirder if the data is no longer buffered and is a live stream, i get the following issue where it both sends and drops the data, but ultimately the influx processor is dropping the data:

![Screenshot from 2023-09-12 17-17-24](https://github.com/influxdata/nifi-influxdb-bundle/assets/44924639/69846968-bfe7-4705-966d-95e12223d1c2)

my goal is to ensure that the json data is pushed to Influx using the timestamp of the data itself and not the time in which influx receives the data

as you can see the timestamp in which influx is processing the data can differ to that of when data has to be buffered due to a high volume of data that is being processed by NiFi:

![image](https://github.com/influxdata/nifi-influxdb-bundle/assets/44924639/f8d512a8-f8e3-4e3d-a240-bd7a635e0fbc)

but why would it send then drop the data when using the "timestamp" attribute as the time field vs using the "time" attribute as the time field when they are one and the same value, but as mentioned before the only difference is that I have a timestamp field in my json data

could it be that the timestamp field is still in epoch format within the json data?

and if so do you have any ideas how I can update that field  - I was thinking that was what the UpdateAttribute processor was meant to do

any help would be appreciated :)

**Comment by oneofthemany** [comment]
UPDATE:

I have 3 options for timestamps:

`{"timestamp":1695034779583,""date_time_nano":"2023-09-18T10:59:39.583730252Z","epoch_time_nano":1695034779583730252}`

I cant seem to get any  of them to work.

I have tried the easy path which was to use JSONTreeReader with a value set against the Timestamp Format as follows:

`"yyyy-MM-dd'T'HH:mm:ss.SSSSSSSSS'Z'"`

but I get this error:

11:09:16 UTC  ERROR 
`PutInfluxDatabaseRecord_2[id=948042a2-018a-1000-6d82-6057eaf604a2] influxdb.error.message: For input string: "2023-09-18T10:59:39.583696710Z"`

I am left scratching my head here so any help would be appreociated

**Comment by oneofthemany** [comment]
its fine I solved the issue

the timestamp field needs to be presented to the processor in string format

@bednar - it may be beneficial for other user if someone was to update the wiki to represent this requirement :)

**Comment by Alphaelectric** [comment]
> its fine I solved the issue
> 
> the timestamp field needs to be presented to the processor in string format
> 
> @bednar - it may be beneficial for other user if someone was to update the wiki to represent this requirement :)

Hi there, it seems we have run into a very similar issue. Could you elaborate on what exactly you changed to present the timestamp to the processor in string format?

Thanks a bunch

**Comment by oneofthemany** [comment]
> > its fine I solved the issue
> > 
> > the timestamp field needs to be presented to the processor in string format
> > 
> > @bednar - it may be beneficial for other user if someone was to update the wiki to represent this requirement :)
> 
> Hi @oneofthemany , it seems we have run into a very similar issue. Could you elaborate on what exactly you changed to present the timestamp to the processor in string format?
> 
> Thanks a bunch

I used jolt transform to set the field  toString

I'm on mobile at the moment, but if you need to know how to do that let me know

**Comment by Alphaelectric** [comment]
> 
> I used jolt transform to set the field toString
> 
> I'm on mobile at the moment, but if you need to know how to do that let me know

Hey @oneofthemany, 

thanks a lot. Yeah, your solution would definitely help a lot. Below I have posted the JoltTransform which I used to create the UTC timestamp. The Jsonrecordwriter is set to include the variable "timestamp" as type "string". I thought that would be sufficient but obviously it's not. 

<img width="894" alt="image" src="https://github.com/influxdata/nifi-influxdb-bundle/assets/36924666/0ce2212f-cef1-4c9f-bebe-50ea6b5a9127">

Do you see how I could modify the jolttransform to incorporate your solution?

Many thanks!!

**Comment by oneofthemany** [comment]
> > 
> > I used jolt transform to set the field toString
> > 
> > I'm on mobile at the moment, but if you need to know how to do that let me know
> 
> Hey @oneofthemany, 
> 
> thanks a lot. Yeah, your solution would definitely help a lot. Below I have posted the JoltTransform which I used to create the UTC timestamp. The Jsonrecordwriter is set to include the variable "timestamp" as type "string". I thought that would be sufficient but obviously it's not. 
> 
> The flow works somewhat like this: 
> - import csv-record
> - retrieve "deviceid", "datapoint", "unit", "value", "date" and "time".
> - combine "date" and "time" to "timestamp" and drop "date" and "time"
> - update JSON with "deviceid", "datapoint", "unit", "value" and "timestamp" 
> - load putinfluxdatabaserecord_2 with the above properties
> 
> <img width="894" alt="image" src="https://github.com/influxdata/nifi-influxdb-bundle/assets/36924666/0ce2212f-cef1-4c9f-bebe-50ea6b5a9127">
> 
> Do you see how I could modify the jolttransform to incorporate your solution?
> 
> Many thanks!!
> 

It would help to understand why you can't attach a timestamp within your data

What exactly are you doing?

**Comment by Alphaelectric** [comment]
> It would help to understand why you can't attach a timestamp within your data
> 
> What exactly are you doing?

I am getting meter readings in csv-format from all kinds of electrical meters, sensors, etc. Each csv contains measured values from datapoints at the time of reading. I have used this workflow before in conjunction with a postgresql database and wanted to make the switch to influxdb for more performant data analysis. 

I can import the data when ignoring the timestamp of the meter reading but this doesn't fulfill the usecase as I am not seeing the data from the point it was measured but from the point it was imported to influx. 

I need the processor to accept my supplied "timestamp" property. 

I hope this helps. If you like, I can supply the XML file of the flow file.

**Comment by oneofthemany** [comment]
Have you thought of just adding a timestamp column to the CSV and using telegraf to ingest?

I'm away at the moment but I'll be able to give you the NiFi solution when I get back on Monday

**Comment by Alphaelectric** [comment]
> Have you thought of just adding a timestamp column to the CSV and using telegraf to ingest?
> 

Unfortunately, I cannot control the CSV structure as it is proprietary to data loggers we have in the field. We can easily adjust nifi to support different brands and sources and funnel them through the same flow. 

> I'm away at the moment but I'll be able to give you the NiFi solution when I get back on Monday

Thank you 👍

**Comment by oneofthemany** [comment]
@Alphaelectric can you send me the actual format of the time and date fields within your csv as i will need to understand that ahead of giving you a solution

**Comment by Alphaelectric** [comment]
> @Alphaelectric - so you are trying to inject a timestamp as your csv does not have one?
> 
> am i correct in my thinking?

My original csv does come with a separate date and a separate time field. It identifies the meter reading time for each meter register  on a given date (see attached file). 

[](url)
[Saia_Stromzaehler_230816_104128.csv](https://github.com/influxdata/nifi-influxdb-bundle/files/12785550/Saia_Stromzaehler_230816_104128.csv)
We do  have a solid workflow with Postgres where we used concat on date and time in a Jolttransform to create a timestamp that is easily inserted in the Postgres database. 

We modified this Jolttransform as seen in the screenshot above to separate the date into year, month and day and time into hours, minutes and seconds and moving them into a temporary array, then joining everything into one single timestamp in UTC format (adding 000000000Z for NS-precision).

That's the timestamp we need attached to the meter readings.

**Comment by oneofthemany** [comment]
Well I'm not using date and time string data, I'm using epoch time sent as a string as that's the only way I could get the processor to accept a json timestamp.

Epoch time as NS is usually split in 2 with a full stop as a separator: 10 digits for date time in seconds and the remaining 9 for the ms, us, ns.


You will need to use the UpdateAttribute and UpdateRecord processor to convert your timestamp to epoch and then use jolt transform to ensure the 19 digit is a string

I can give you more on that tomorrow when I'm at my desk

**Comment by Alphaelectric** [comment]
> Well I'm not using date and time string data, I'm using epoch time sent as a string as that's the only way I could get the processor to accept a json timestamp.
> 
> Epoch time as NS is usually split in 2 with a full stop as a separator: 10 digits for date time in seconds and the remaining 9 for the ms, us, ns.
> 
> 
> You will need to use the UpdateAttribute and UpdateRecord processor to convert your timestamp to epoch and then use jolt transform to ensure the 19 digit is a string
> 
> I can give you more on that tomorrow when I'm at my desk
> 

Oh man, how did you ever find out about that! This info is *badly* missing from the documentation.

So glad there is hope after all. Thanks a lot!

**Comment by Alphaelectric** [comment]
@oneofthemany 

Following your advice I did make some progress. I converted my date and time field to epoch time using UpdateRecord

${field.value:toDate('yyyy-MM-dd HH:mm:ss'):toNumber():divide(1000)}

My new timestamp has 10 digits and like in your case, influx rejects it as being beyond retention policy:

"2023-10-04 06:55:59,010 ERROR [Timer-Driven Process Thread-1] o.i.n.p.PutInfluxDatabaseRecord_2 PutInfluxDatabaseRecord_2[id=cbe3b51c-018a-1000-6d5c-3ea160436312] Failed to insert into influxDB due to HTTP status code: 422; Message: failure writing points to database: partial write: points beyond retention policy dropped=22"

Now all that is left to do is to convert it into NS format.

**Comment by oneofthemany** [comment]
No you don't need to convert

Just make sure it's presented as a string and change the value in the processor to "S"

**Comment by Alphaelectric** [comment]
> @Alphaelectric No you don't need to convert
> 
> Just make sure it's presented as a string and change the value in the processor to "S"
> 
> The reason it's being dropped is the value of the time stamp has the wrong amount digits

Got it! It's working now.

Thanks a lot for helping me out here!

**Comment by oneofthemany** [comment]
> > @Alphaelectric No you don't need to convert
> > Just make sure it's presented as a string and change the value in the processor to "S"
> > The reason it's being dropped is the value of the time stamp has the wrong amount digits
> 
> Got it! It's working now.
> 
> Thanks a lot for helping me out here!

Sure no worries :)
