### ISSUE TITLE
 GetInfluxDatabaseRecord_2 Processor Fails to Copy Attributes on Splitting Result Sets

### ISSUE THREAD

**Issue by ulbi** [influxdata/nifi-influxdb-bundle#144]
### NiFi Version
1.23.2 - Processor version 1.25.0

### Processor Name
`GetInfluxDatabaseRecord_2`

### Description
The `GetInfluxDatabaseRecord_2` processor in Apache NiFi exhibits inconsistent behavior in handling flow file attributes when splitting result sets. When the processor splits a large result set into chunks (e.g., of 1000 elements), it fails to copy the original flow file's attributes to the new flow files generated post-split. However, if there is no split (i.e., the result set is small enough to not require splitting), the processor retains the attributes as expected.

### Expected Behavior
When the `GetInfluxDatabaseRecord_2` processor splits a flow file, each new flow file resulting from the split should retain the attributes of the original flow file.

### Actual Behavior
The processor only retains the attributes if no splitting occurs. In cases where the result set is large enough to be split into multiple flow files, the newly created flow files lack the original attributes.

### Steps to Reproduce
1. Configure a `GetInfluxDatabaseRecord_2` processor to query an InfluxDB instance where the expected result set is large enough to require splitting (e.g., more than 1000 records).
2. Ensure the processor is set to split the result set into chunks of 1000 elements.
3. Observe the attributes of the original flow file and compare them with the attributes of the flow files generated post-split.

### Example Scenario
- A flow file with custom attributes (e.g., `source: sensor_data`, `type: temperature`) is passed to the `GetInfluxDatabaseRecord_2` processor.
- The processor is set to retrieve a large data set from InfluxDB, resulting in the data being split into multiple flow files.
- The original flow file's attributes are not present in the new flow files created after the split.

### Impact
This behavior impedes workflows where attribute retention across splits is crucial for subsequent processing steps.

### Additional Context
- A potential workaround involves using a combination of attribute caching strategies, but this adds complexity and overhead to the flow.

**Comment by bednar** [comment]
Hi @ulbi,

Thanks for using our bundle and report your issue. Is this something you would be willing to help with? All PR is welcome and we will be happy to review your submission.

Regards

**Comment by ulbi** [comment]
Hi @bednar ,

thanks for your reply - I can give a try, it's a matter of time ;-). I just scanned through the code and might have found the [place](/influxdata/nifi-influxdb-bundle/tree/master/nifi-influx-database-processors/src/main/java/org/influxdata/nifi/processors/internal/AbstractGetInfluxDatabase_2.java) to change in 

```
       private QueryProcessor(final String org,
                               final Query query,
                               final long recordsPerFlowFile,
                               final FlowFile flowFile,
                               final boolean createdFlowFile, final ProcessContext context,
                               final ProcessSession session) {
            this.flowFiles.add(flowFile);
            if (recordsPerFlowFile == -1 || createdFlowFile) {
                this.flowFile = flowFile;
            } else {
                this.flowFile = session.create();
                this.flowFiles.add(this.flowFile);
            }
```

Cheers,
René

**Comment by bednar** [comment]
@ulbi, thank you for your efforts. It would be wonderful if this could be accomplished.

**Comment by ulbi** [comment]
@bednar Did the fix - just let me know if there is something missing

**Comment by bednar** [comment]
@ulbi Thank you for your patience and contribution. I've reviewed your Pull Request and everything looks great! Therefore, I will be merging your PR into the master branch shortly. Your contributions are much appreciated, and we look forward to more of your valuable input in the future. If you have any more changes or updates in mind, please feel free to share.
