### ISSUE TITLE
GetInfluxDatabase_2 10 seconds timeout problem

### ISSUE THREAD

**Issue by Marco-Colombi** [influxdata/nifi-influxdb-bundle#158]
Hi there,

I'm experiencing a problem with the processor GetInfluxDatabase_2 in the 1.24.0 bundle version. The NiFi version is 1.19.0.

The Flux query that I'm sending takes more than 10 seconds, but after 10 seconds of elaboration the request times out, logging the error 
 - "Failed to execute Flux query due SocketTimeoutException to class Query" 
- "java.net.SocketTimeoutException: timeout Caused by: java.net.SocketException: Socket closed".

I tried to change the parameter "**InfluxDB Max Connection Time Out (seconds)**" in the corresponding StandardInfluxDatabaseService_2 controller service to 60 seconds (or higher), but it still times out after 10 seconds.

![immagine](https://github.com/influxdata/nifi-influxdb-bundle/assets/56490374/6a9548cc-45ca-4e99-b78f-cc410bba67b0)

It seems like it doesn't see this parameter for the timeout.

Do you know what is possibly causing this issue? Am I missing something?

Thanks a lot for your support. Any help would be much appreciated!

**Comment by bednar** [comment]
Hi @Marco-Colombi,

thanks for using our bundle.

Is this something you would be willing to help with? All PR is welcome and we will be happy to review your submission.

Best Regards

**Comment by Marco-Colombi** [comment]
Hi @bednar,

I was not able to understand where is the issue in your code. From your side, did you try to look at it and understand what is happening? 

Thank you and kind regards

**Comment by bednar** [comment]
@Marco-Colombi, I think that the problem is here: https://github.com/influxdata/nifi-influxdb-bundle/blob/03e5385da2f56cd71616e0ba9b6d4940a6cf23ad/nifi-influx-database-utils/src/main/java/org/influxdata/nifi/util/InfluxDBUtils.java#L326

The should be something like:

```java
OkHttpClient.Builder builder = new OkHttpClient.Builder()
        .writeTimeout(connectionTimeout, TimeUnit.SECONDS)
        .connectTimeout(connectionTimeout, TimeUnit.SECONDS)
        .readTimeout(connectionTimeout, TimeUnit.SECONDS);
```

Regards

**Comment by bednar** [comment]
Hi @Marco-Colombi,

I'm pleased to let you know that the issue you reported has been addressed in our latest pull request, which you can view here: [PR #163](https://github.com/influxdata/nifi-influxdb-bundle/pull/163) by @alespour.

To ensure that the fix resolves the issue as expected, could you please test it using our snapshot build? You can download the snapshot from the following link: [NiFi-InfluxDB Bundle v1.29.0-SNAPSHOT](https://github.com/influxdata/nifi-influxdb-bundle/releases/tag/v1.29.0-SNAPSHOT).

Your feedback will be invaluable in confirming that everything is working correctly before we proceed with a more formal release. Please let us know how it goes.

Best Regards
