### ISSUE TITLE
Uploading to central maven repository

### ISSUE THREAD

**Issue by drewyh999** [influxdata/nifi-influxdb-bundle#174]
Hey team

I found that the binaries are not yet in the central maven repo(Or it's already in there but I fail to find it?), which makes updating them kind of not convenient. would you consider put them into the maven repo in the future?

BR

**Comment by bednar** [comment]
Hi @drewyh999,

Thank you for using our bundle. Could you share how you are integrating Apache NiFi with the Maven repository?

Best regards

**Comment by drewyh999** [comment]
Hi @bednar 

Thanks for the fast reply! We have our own custom built processor written in Java and would pull dependencies from maven repository. I was just thinking if it is possible to integrate the influxdb processors without having to manually copy the nar file to the nifi-current/lib directory and that's why I create this issue here. Also, if it is possible to install through maven, we would not have to put the nar file in the git and less effort when updating. 

BR

**Comment by drewyh999** [comment]
Your right, this probably should not related to maven. All good, I think I'll use a script to do that, sry for bothering. Thanks for contributing to this bundle! It's been a crucial part of our flow :)

**Comment by bednar** [comment]
you are welcome

**Comment by bednar** [comment]
Hi @drewyh999,

Unfortunately, we don't have any better suggestions at the moment.

Best regards

**Comment by drewyh999** [comment]
Hi @bednar 

Do you plan to maintain it in a maven repository? We tried to automatically download it directly from the github release page, however, the problem with this approach is that if the download link changes, our building pipeline will fail. If your bundle is in the central maven repository, we can directly use maven to pull it and since we setup an azure artifact feed, that package will also be cached in our artifact feed. This way we don't have worry about if the download link is changed and we can do easy version upgrade and management and it is just much more stable

Thank you for your time!

BR

**Comment by bednar** [comment]
Hi @drewyh999,

Thank you for reaching out. Currently, we do not have plans to integrate the bundle into the Maven Repository. However, you can reliably access the releases directly from GitHub. The release links on GitHub are stable, ensuring you can consistently download the specific versions you need without worrying about link changes.

Here is an example of how you can construct a stable download link for the NiFi InfluxDB bundle using a bash script:

```bash
NIFI_BUNDLE_VERSION="1.29.0"
NIFI_BUNDLE_URL="https://github.com/influxdata/nifi-influxdb-bundle/releases/download/v$NIFI_BUNDLE_VERSION/nifi-influx-database-nar-$NIFI_BUNDLE_VERSION.nar"
```

This method allows you to dynamically specify the version of the bundle you wish to download, ensuring you always have access to the latest or required version.

If integrating the bundle into the Maven Central repository is crucial for your project, we can consider adding this issue to our backlog. However, please note that we do not currently have a concrete timeline for this integration.

Let us know if this approach works for you or if there are any other ways we can assist.

Best Regards
