### ISSUE TITLE
Line Protocol Writer

### ISSUE THREAD

**Issue by dp1140a** [influxdata/nifi-influxdb-bundle#19]
Currently we have a LineProtocolReader Service, but it would be helpful to also have a LineProtocolWriter Service.  

There are many cases where I may wish to write Line Protocol directly out of my Nifi Flow say to Kafka or another downstream listener without having to convert back ad forth to Avro, CSV or JSON.

**Comment by bednar** [comment]
So We need create a `Record Writer` that should be able to serialize record data to Line Protocol?

**Comment by dp1140a** [comment]
That would be the dream man.  It could also be used to replace the AvroRecord reader and writer service in flow.  So now we have Line protocol straight through.

**Comment by bednar** [comment]
Ok, I will create the `InfluxLineProtocolRecordSetWriter`. The documentation will be looks like:

----
### InfluxLineProtocolRecordSetWriter

Writes the contents of a RecordSet as Line Protocol. The configured  writer is able to make Line Protocol by the Expression Language that  reference each of the fields that are available in a Record. Each record in the RecordSet will be separated by a single newline character.

#### Properties

| Property | Description |
| --- | --- |
| **Measurement** | The name of the measurement. If the Record contains a field with measurement property value, then value of the Record field is use as InfluxDB measurement |
| Tags | A comma-separated list of record fields stored in InfluxDB as 'tag' |
| Missing Tag Behavior | If the specified tag is not present in the document, this property specifies how to handle the situation. Options: **Ignore**, Fail. |
| **Fields** | A comma-separated list of record fields stored in InfluxDB as 'field'. At least one field must be defined |
| Missing Field Behavior | If the specified field is not present in the document, this property specifies how to handle the situation.  Options: **Ignore**, Fail. |
| Timestamp field | A name of the record field that used as a 'timestamp' |
| **Timestamp precision** | The timestamp precision is ignore when the 'Timestamp field' value is 'java.util.Date' |
| **Complex Field Behavior** | Indicates how to handle complex fields, i.e. fields that do not have a primitive value. Options: **Text**, Fail.  |
| **Null Values Behavior** | Indicates how to handle null fields, i.e. fields that do not have a defined value. Options: **Ignore**, Fail.  |
----

What do you think about it?

**Comment by bednar** [comment]
Hi @dp1140a,

The `InfluxLineProtocolRecordSetWriter` is prepared and you could try it in `v1.1-SNAPSHOT` release - https://github.com/influxdata/nifi-influxdb-bundle/releases.

The release `v1.1` is almost prepare and after fix #20 we will be ready to release it.
