### ISSUE TITLE
 PutInfluxDatabase timestamp precision

### ISSUE THREAD

**Issue by lssilva** [influxdata/nifi-influxdb-bundle#20]
Currently it seems that PutInfluxDatabase only supports nano-seconds but InfluxDB API provides the possibility to define in the url precision=ms this doesn't seems to work on the Nifi process. 
 
Documentation 
> The timestamp (last field) should be in nano-seconds resolution.

**Comment by bednar** [comment]
Yes, is is true. 

`PutInfluxDatabase` currently doesn't support custom precision as is in `PutInfluxDatabaseRecord`.

I will add optional property `Timestamp precision` into `PutInfluxDatabase` processor:

| Property | Description |
| --- | --- |
| **Timestamp precision** | The precision of the time stamps. InfluxDB assumes that timestamps are in nanoseconds if you do not specify precision. |


What do you think about it?

**Comment by lssilva** [comment]
looks good

**Comment by bednar** [comment]
Hi @lssilva ,

The `PutInfluxDatabase` is updated and you could try it in `v1.1-SNAPSHOT` release - https://github.com/influxdata/nifi-influxdb-bundle/releases.

The release `v1.1` is almost prepare and probably I will release it tomorrow.
