### ISSUE TITLE
Is is possible to use flowfile attribure as influxdb tags, fileds?

### ISSUE THREAD

**Issue by gogangipark** [influxdata/nifi-influxdb-bundle#25]
when creating the lineprotocol record of influxdb, i would like to use Use attribute of the flowfile 
However, if you use the attribute of flowfile at making lineprotocol,  cant not find the variable.

Is it possible to use the attribute of flowfile as a variable of lineprotocol?

**Comment by bednar** [comment]
Hi @gogangipark,

Currently the [PutInfluxDatabaseRecord](https://github.com/influxdata/nifi-influxdb-bundle#putinfluxdatabaserecord) only evaluates tags and fields over Apache NiFi Record.

You could update your record by the [UpdateRecord](https://nifi.apache.org/docs/nifi-docs/components/org.apache.nifi/nifi-standard-nar/1.6.0/org.apache.nifi.processors.standard.UpdateRecord/index.html) processor. 

To add a tag field to your record use following configuration:

![tag_from_attribute](https://user-images.githubusercontent.com/455137/61209799-0573fb80-a6fb-11e9-951b-248945a5fca6.png)

Is it OK for you?

**Comment by gogangipark** [comment]
Thank you for your reply.
I did implement it successfully as your advice.
