### ISSUE TITLE
Cannot use TLS connection with PutInfluxDatabase_2

### ISSUE THREAD

**Issue by recype-io** [influxdata/nifi-influxdb-bundle#55]
I cannot get the connection to an InfluxDB2 server (via Apache Reverse Proxy with TLS and Client-Auth) to work.

I always get this error, when PutInfluxDatabase_2/StandardInfluxDatabaseService_2 tries to establish a connection:
```
2021-05-11 07:51:48,338 ERROR [Timer-Driven Process Thread-2] o.i.nifi.processors.PutInfluxDatabase_2 PutInfluxDatabase_2[id=fe4d3e03-0177-1000-218e-e4211ca049d3] Failed to insert into influxDB due to PK
IX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target: com.influxdb.exceptions.InfluxException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
com.influxdb.exceptions.InfluxException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at com.influxdb.internal.AbstractRestClient.execute(AbstractRestClient.java:84)
        at com.influxdb.client.internal.WriteApiBlockingImpl.write(WriteApiBlockingImpl.java:229)
...
```

However, the **same** StandardRestrictedSSLContextService with the same target URL does work, when used in a GetHTTP processor.

So I'm quite certain that the TLS configuration is correct.

Are there any known issues with the https client used by StandardInfluxDatabaseService_2 regarding TLS client authentication, multi level CA hierarchies etc.?

**Comment by bednar** [comment]
Hi @recype-io,

thanks for using our `NiFi bundle`. 

There isn't know issue for TLS configuration. In our test scenario we uses `StandardSSLContextService` instead of `StandardRestrictedSSLContextService`. Something like: 

![image](https://user-images.githubusercontent.com/455137/112616432-0479f380-8e24-11eb-9290-b7f353ab7591.png)

Can you test your configuration with `StandardSSLContextService`?

Regards

**Comment by bednar** [comment]
It is hard to say... from my POV it should be correct.

Maybe there is a problem how is configured SSL connection for an underlayer HTTP client. The `GetHTTP` uses Apache HTTP client, but the `PutInfluxDatabase_2` uses OkHTTP client. 

Can you check that the `SSLContextService` works with `InvokeHTTP` processor? Something similar to `curl` query:

```
curl -i -X GET https://my-influxdb-behind-proxy/ping
```

**Comment by recype-io** [comment]
Ok, so I found a viable workaround:

Instead of the PutInfluxDatabase_2 processor with the StandardInfluxDatabaseService_2, I now use a 
ConvertRecord processor with an InfluxLineProtocolRecordSetWriter to convert JSON to LineProtocol.

Then an UpdateAttribute processor, mainly to set the Authorization token.
And finally an InvokeHTTP processor to send the date to InfluxDB.

The only thing that is not ideal with the approach: The authentication token cannot be read from a protected field in Nifi.

From my point of view, this is not an urgent issue anymore.

**Comment by bednar** [comment]
@recype-io I'm glad that you found the solution. I want to improve our implementation of `SSLContextFactory`: https://github.com/influxdata/nifi-influxdb-bundle/blob/da22b6f98b5a5134419b07280dfdfd414a235911/nifi-influx-database-services/src/main/java/org/influxdata/nifi/services/AbstractInfluxDatabaseService.java#L49

If I will prepare test bundle Are you able to test it with your configuration?

**Comment by recype-io** [comment]
Yes, I might be able to test a new version.

**Comment by bednar** [comment]
Hi @recype-io, 

I've prepared PR #58 with fix. Are you able to test the following snapshot bundle: https://github.com/influxdata/nifi-influxdb-bundle/pull/58#issuecomment-851461906?

Regards
