### ISSUE TITLE
Possibility to use Processorgroup parameters

### ISSUE THREAD

**Issue by BIGabor** [influxdata/nifi-influxdb-bundle#56]
Hi InfluxDB Team,

as I see, I can't use ProcessorGroup Params in the configs. It's a new thing in NiFi. Could you please check, if it could be implemented?

BR,
Gabor

**Comment by bednar** [comment]
Hi @BIGabor,

thanks for suggestion. 

Do you have a detail information how is ProcessorGroup used in others Processors? I can't find any related information.

Regards

**Comment by BIGabor** [comment]
I'm closing this too, as you already allowing to use the PARAM option too, so we can use our Processor Group Contexts too.
