### ISSUE TITLE
Converting time

### ISSUE THREAD

**Issue by BIGabor** [influxdata/nifi-influxdb-bundle#59]
Hi,

it looks, I have a problem with time-conversion.
Input JSON : 
only the date part:
"ActiveFromUtc":"2021-05-28T17:45:45.950Z"}
As I see, in Influx docs, precision ms means, that it will change the last numbers to 000, but not trimming it, so the timestamps should be sent with NS length. I set it to NS, in Putinfluxdb2 processor, but in the log it's always ms. I think it comes from the Jsontreereader, as I configured it like:
yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
and also tried:
yyyy-MM-dd'T'HH:mm:ss.SSSSSSSSS'Z'
No luck. 
Could you please help on this?

PutInfluxDatabaseRecord_2[id=76cf35a8-ae9d-1396-b2c1-3b5bcf0e026b] InfluxDB connection created for host https://influxdb-kafka.com:/
--
6:46:08.670 PM | INFO | OkHttpClient | --&gt; POST https://influxdb-kafka.com/api/v2/write?org=asw&amp;bucket=kafka2&amp;precision=ms
6:46:08.670 PM | INFO | OkHttpClient | Content-Type: text/plain; charset=utf-8
6:46:08.670 PM | INFO | OkHttpClient | Content-Length: 76
6:46:08.670 PM | INFO | OkHttpClient | Content-Encoding: identity
6:46:08.670 PM | INFO | OkHttpClient | Accept: application/json
6:46:08.670 PM | INFO | OkHttpClient | User-Agent: influxdb-client-java/1.11.0
6:46:08.670 PM | INFO | OkHttpClient | &nbsp;
6:46:08.670 PM | INFO | OkHttpClient | Test_sis,Type.ack=test_key_13 CustomId=7i 1622223945950
6:46:08.670 PM | INFO | OkHttpClient | --&gt; END POST (76-byte body)
6:46:08.845 PM | INFO | OkHttpClient | &lt;-- 204 No Content https://influxdb-kafka.com/api/v2/write?org=asw&amp;bucket=kafka2&amp;precision=ms (175ms)
6:46:08.846 PM | INFO | OkHttpClient | Date: Fri, 28 May 2021 16:46:08 GMT
6:46:08.846 PM | INFO | OkHttpClient | Connection: keep-alive
6:46:08.846 PM | INFO | OkHttpClient | &lt;-- END HTTP

**Comment by BIGabor** [comment]
BR,
Gabor

**Comment by bednar** [comment]
Hi @BIGabor,

the default precision for the `PutInfluxDatabase_2` is `ns`. Could you share how looks like your `PutInfluxDatabase_2` configuration?

Regards

**Comment by BIGabor** [comment]
Hi @bednar

**Comment by BIGabor** [comment]
Hi @bednar 

Sorry, it was a copy-paste, and it closed this case.
` "type": "org.influxdata.nifi.processors.PutInfluxDatabaseRecord_2",
                "properties": {
                    "influxdb-tags": "type",
                    "influxdb-tags-field-behavior": "IGNORE",
                    "influxdb-timestamp-field": "timestamp",
                    "influxdb-measurement": "measurement",
                    "influxdb-log-level": "BODY",
                    "influxdb-fields-field-behavior": "IGNORE",
                    "influxdb-fields": "value",
                    "influxdb-null-behavior": "IGNORE",
                    "influxdb-bucket": "kafka2",
                    "influxdb-max-records-size": "1 MB",
                    "influxdb-service": "99892339-ee02-326d-89af-9c2e99f8294f",
                    "influxdb-write-precision": "NS",
                    "record-reader": "e533ddfb-5e3c-38c0-920d-5ebedde04889",
                    "influxdb-enable-gzip": "false",
                    "influxdb-org": "torg",
                    "influxdb-complex-field-behavior": "TEXT"
                },`

**Comment by BIGabor** [comment]
My other question would be, how to reference to a nested object?
Example (formatted avro, converted from JSON):
` {
  "typecol" : "x1",
  "Userinfo" : {
    "UserId" : "23553",
    "UserStreetId" : 193,
    "Logintime" : "2021-06-18T08:39:32.097Z",
    "Subtype" : {
      "Login" : "true",
      "Locked" : "false",
      "Logincount" : 8424,
      }
    }
    }`
    
I already opened a ticket regarding the processor group parameters.
The idea: give some params, like value: Userinfo.Subtype.Logincount, timestamp as logintime, etc. So no burned in converts in JSONreader, but a JSONtreereader, or in worst case a FlattenJSON, and I can send it with params to Influx. Usually, that's how I work with NiFi. In this way I can build my Bucket much faster/easier.
Other way, to write it in a programming language

BR,
Gabor

**Comment by bednar** [comment]
Hi @BIGabor,

you can use nested dynamic properties. See this example: https://github.com/influxdata/nifi-influxdb-bundle#twitterjsonreader-configuration.


Regards

**Comment by BIGabor** [comment]
This name, dynamic is strange. You have to type it in as an extra attribute to the processor, you can't send those as parameters, so for me it's not dynamic. Now I started my process again with flatten, than it's "dynamic". On the timestamp I'm not sure. Update within 1 hour.

**Comment by BIGabor** [comment]
BTW, can I a pass a field with content: "2021-06-18T08:40:54.023Z" as timestamp?

**Comment by BIGabor** [comment]
I'm using JSONTreeReader, and put this to the Timestamp format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"

**Comment by bednar** [comment]
> I'm using JSONTreeReader, and put this to the Timestamp format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"

I've tested this format and it will be works.

```java
Date parsed = DataTypeUtils.getDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
				.parse("2021-06-18T08:40:54.023Z");
```

**Comment by BIGabor** [comment]
Hi Bednar, I can confirm, it works. :)
So no problems with it.

**Comment by oneofthemany** [comment]
Hi @bednar

I am having the same issue where my timestamp is as follows:

`{"time": "2023-09-18T09:44:12.336610736Z"}`

but when i set my JSONTreeReader to be as follows:

`yyyy-MM-dd'T'HH:mm:ss.SSSSSSSSS'Z'`

i get the following error in the in the PutInfluxDatabaseRecord_2 processor:

```
10:10:31 UTC  ERROR 
PutInfluxDatabaseRecord_2[id=a7a731e5-018a-1000-54f7-5d6802329f12] influxdb.error.message: For input string: "2023-09-18T09:57:52.681331628Z"
```

Any help would be appreciated

:)
