### ISSUE TITLE
Use case oriented README.md

### ISSUE THREAD

**Issue by ivankudibal** [influxdata/nifi-influxdb-bundle#9]
In the introductory part README.md should contain structured by use cases:

Use case 1: In the Nifi collect metrics from outside world (using  no telegraf) and write data into influxdb

Use case 2: Configure telegraf to produce data into Nifi in order to transform the records, such as to remove some irrelevant fields, fork traffic to write to multiple DBs

Use case 3 Use Nifi as data lossless middleman between Telegraf and InfluxDB.
  * back pressure
  * reliable queues
  * nifi cluster

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
